version: '3.9'

services:
  mssql-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrongPassword123"
    volumes:
      - mssql-data:/var/opt/mssql
    networks:
      - backend
    restart: always

  aspnet-api:
    build:
      context: ./aspnet-api
      dockerfile: Dockerfile
    container_name: aspnet-api
    depends_on:
      - mssql-db
    ports:
      - "5000:80"
    environment:
      ConnectionStrings__DefaultConnection: "Server=mssql-db;Database=yumlsschooldb;User Id=sa;Password=YourStrongPassword123;Encrypt=False;TrustServerCertificate=True;"
      ASPNETCORE_ENVIRONMENT: "Development"
    networks:
      - backend
    restart: always

  django-app:
    build:
      context: ./django-app
      dockerfile: Dockerfile
    container_name: django-app
    depends_on:
      - mssql-db
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    environment:
      DJANGO_SETTINGS_MODULE: "kursyamls.settings"
    networks:
      - backend
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - django-app
      - aspnet-api
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - static_volume:/app/static
      - media_volume:/app/media
    networks:
      - backend
    restart: always

  init-mssql:
    image: mcr.microsoft.com/mssql-tools
    container_name: init-mssql
    depends_on:
      - mssql-db
    networks:
      - backend
    entrypoint: >
      /bin/bash -c "
      echo 'Waiting for MSSQL...';
      for i in {1..30}; do
        /opt/mssql-tools/bin/sqlcmd -S mssql-db -U sa -P 'YourStrongPassword123' -Q 'SELECT 1' && break;
        sleep 2;
      done;
      echo 'Creating database...';
      /opt/mssql-tools/bin/sqlcmd -S mssql-db -U sa -P 'YourStrongPassword123' -Q \"IF DB_ID('yumlsschooldb') IS NULL CREATE DATABASE yumlsschooldb\";
      echo 'Done.'"
    restart: "no"

  init-db-full:
    image: mcr.microsoft.com/mssql-tools
    container_name: init-db-full
    depends_on:
      - mssql-db
    volumes:
      - ./mssql/init.sql:/init.sql:ro
    networks:
      - backend
    entrypoint: >
      /bin/bash -c "
      echo 'Waiting for MSSQL...';
      for i in {1..30}; do
        /opt/mssql-tools/bin/sqlcmd -S mssql-db -U sa -P 'YourStrongPassword123' -Q 'SELECT 1' && break;
        sleep 2;
      done;
      echo 'Executing script...';
      /opt/mssql-tools/bin/sqlcmd -S mssql-db -U sa -P 'YourStrongPassword123' -i /init.sql;
      echo 'Done.'"
    restart: "no"

volumes:
  mssql-data:
  static_volume:
  media_volume:

networks:
  backend:
